### ISSUE TITLE
增量运行不仅没有变快，反而速度变慢了

### ISSUE THREAD

**Issue by GothicFox** [typ0520/fastdex#86]
typ0520您好，我这边最近使用了一下fastdex，然后遗憾的是在我自己工程里面并没有特别有效果，有时候反而会比全编还慢。。
由于工程不太方便发上来，所以就用fastdex自己提供的sample来做个实验，我自己生成了一些java类，来模拟一下很多个java类的情况，总共大概有15000个java类，总共90000个方法，如果用multidex差不多要2个dex的样子。

我把这些类直接拷贝到sample下面的app里面，并且在mainactivity oncreate最后来进行调用，类似下面这样：

        new Foo149().foo4();
        new com.nikitakozlov.gradlebuildexperiment.generated2.package_0.Foo149().foo4();
        new com.nikitakozlov.gradlebuildexperiment.generated3.package_0.Foo149().foo4();

然后我还在 app的build.gradle里面加了这个选项，不然编译过程中会oom：

dexOptions {
        javaMaxHeapSize "4g"
    }

然后我开始实验，

第一次 全编，就直接运行了Android studio的 运行按钮，另外我的Android studio 是3.0版本：

==fastdex copy meta info: 
from: /Users/username/Desktop/fastdex/sample/app/build/fastdex/Debug/fastdex-meta-info.json
into: /Users/username/Desktop/fastdex/sample/app/build/intermediates/assets/debug/fastdex-meta-info.json

:app:assembleDebug

BUILD SUCCESSFUL in 6m 43s
70 actionable tasks: 42 executed, 28 up-to-date
Task spend time:
     68ms  :app:processDebugResources
    471ms  :app:fastdexPrepareForDebug
    523ms  :common:compileDebugJavaWithJavac
     50ms  :javalib:compileJava
    233ms  :app:javaPreCompileDebug
 366495ms  :app:compileDebugJavaWithJavac
     55ms  :app:fastdexScanAptOutputForDebug
    819ms  :app:transformClassesWithStackFramesFixerForDebug
   9875ms  :app:transformClassesWithDesugarForDebug
  21177ms  :app:transformClassesWithDexForDebug
    287ms  :app:transformNativeLibsWithMergeJniLibsForDebug
    689ms  :app:transformResourcesWithMergeJavaResForDebug
    402ms  :app:packageDebug

    这一次编译花了6分43秒。

然后我在MainActivity oncreate最后多加一个log，然后用./gradlew fastdexDebug重新编译，得到的结果是比之前全量的时间还长。。。这就尴尬了，看了下，发现compileDebugJavaWithJavac用6分多钟。。我自己理解如果只改了Mainacitivity的话应该只需要把mainactivity重新编译就可以了？为何好像都重新编译了一把？

BUILD SUCCESSFUL in 7m 2s
71 actionable tasks: 45 executed, 26 up-to-date
Task spend time:
     75ms  :app:processDebugResources
   7737ms  :app:fastdexPrepareForDebug
 400453ms  :app:compileDebugJavaWithJavac
     70ms  :app:fastdexScanAptOutputForDebug
    904ms  :app:transformClassesWithStackFramesFixerForDebug
   9219ms  :app:transformClassesWithDesugarForDebug
    407ms  :app:transformClassesWithJarMergingForDebug
   1123ms  :app:transformClassesWithDexForDebug
    649ms  :app:fastdexPatchForDebug

于是到这里就不知道问题出在哪里了？是不是我使用的方法有问题？ 还请大神赐教，谢谢

sample工程我加了代码之后好像太大了，有20多MB，github这里不让上传，我用附件发到您邮箱：php12345@163.com了，麻烦看一下，谢谢🙏

**Comment by typ0520** [comment]
加一个配置试试  fastdex{      useCustomCompile = true}发自我的华为手机-------- 原始邮件 --------主题：[typ0520/fastdex] 增量运行不仅没有变快，反而速度变慢了 (#86)发件人：BottleChain 收件人：typ0520/fastdex 抄送：Subscribed typ0520您好，我这边最近使用了一下fastdex，然后遗憾的是在我自己工程里面并没有特别有效果，有时候反而会比全编还慢。。
由于工程不太方便发上来，所以就用fastdex自己提供的sample来做个实验，我自己生成了一些java类，来模拟一下很多个java类的情况，总共大概有15000个java类，总共90000个方法，如果用multidex差不多要2个dex的样子。
我把这些类直接拷贝到sample下面的app里面，并且在mainactivity oncreate最后来进行调用，类似下面这样：
    new Foo149().foo4();
    new com.nikitakozlov.gradlebuildexperiment.generated2.package_0.Foo149().foo4();
    new com.nikitakozlov.gradlebuildexperiment.generated3.package_0.Foo149().foo4();

然后我还在 app的build.gradle里面加了这个选项，不然编译过程中会oom：
dexOptions {
javaMaxHeapSize "4g"
}
然后我开始实验，
第一次 全编，就直接运行了Android studio的 运行按钮，另外我的Android studio 是3.0版本：
==fastdex copy meta info:
from: /Users/username/Desktop/fastdex/sample/app/build/fastdex/Debug/fastdex-meta-info.json
into: /Users/username/Desktop/fastdex/sample/app/build/intermediates/assets/debug/fastdex-meta-info.json
:app:assembleDebug
BUILD SUCCESSFUL in 6m 43s
70 actionable tasks: 42 executed, 28 up-to-date
Task spend time:
68ms  :app:processDebugResources
471ms  :app:fastdexPrepareForDebug
523ms  :common:compileDebugJavaWithJavac
50ms  :javalib:compileJava
233ms  :app:javaPreCompileDebug
366495ms  :app:compileDebugJavaWithJavac
55ms  :app:fastdexScanAptOutputForDebug
819ms  :app:transformClassesWithStackFramesFixerForDebug
9875ms  :app:transformClassesWithDesugarForDebug
21177ms  :app:transformClassesWithDexForDebug
287ms  :app:transformNativeLibsWithMergeJniLibsForDebug
689ms  :app:transformResourcesWithMergeJavaResForDebug
402ms  :app:packageDebug
这一次编译花了6分43秒。

然后我在MainActivity oncreate最后多加一个log，然后用./gradlew fastdexDebug重新编译，得到的结果是比之前全量的时间还长。。。这就尴尬了，看了下，发现compileDebugJavaWithJavac用6分多钟。。我自己理解如果只改了Mainacitivity的话应该只需要把mainactivity重新编译就可以了？为何好像都重新编译了一把？
BUILD SUCCESSFUL in 7m 2s
71 actionable tasks: 45 executed, 26 up-to-date
Task spend time:
75ms  :app:processDebugResources
7737ms  :app:fastdexPrepareForDebug
400453ms  :app:compileDebugJavaWithJavac
70ms  :app:fastdexScanAptOutputForDebug
904ms  :app:transformClassesWithStackFramesFixerForDebug
9219ms  :app:transformClassesWithDesugarForDebug
407ms  :app:transformClassesWithJarMergingForDebug
1123ms  :app:transformClassesWithDexForDebug
649ms  :app:fastdexPatchForDebug
于是到这里就不知道问题出在哪里了？是不是我使用的方法有问题？ 还请大神赐教，谢谢
sample工程我加了代码之后好像太大了，有20多MB，github这里不让上传，我用附件发到您邮箱：php12345@163.com了，麻烦看一下，谢谢🙏

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/typ0520/fastdex","title":"typ0520/fastdex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/typ0520/fastdex"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"增量运行不仅没有变快，反而速度变慢了 (#86)"}],"action":{"name":"View Issue","url":"https://github.com/typ0520/fastdex/issues/86"}}}

**Comment by GothicFox** [comment]
改了之后有这么一个错误：
* What went wrong:
Execution failed for task ':app:fastdexCustomCompileDebugJavaWithJavac'.
> Resolving configuration 'annotationProcessor' directly is not allowed

然后我网上搜了一下，找到这篇文章：https://juejin.im/entry/59a062796fb9a0249471c432

在这两句中间加一句这个就行了应该：

def annotationProcessorConfig = project.configurations.findByName("annotationProcessor")
@+++
        annotationProcessorConfig.setCanBeResolved(true)
@+++
        def isAnnotationProcessor = annotationProcessorConfig != null && !annotationProcessorConfig.empty

**Comment by GothicFox** [comment]
我这里自己本地改了一下，发现好使了现在，谢谢 @typ0520

**Comment by itwen** [comment]
@BottleChain 你在本地改，怎么发布呢

**Comment by typ0520** [comment]
直接执行./gradlew install

**Comment by itwen** [comment]
@typ0520 生成的产物有哪些 怎么引入工程呢

**Comment by typ0520** [comment]
@itwen 使用的地方加上        mavenLocal()

```
buildscript {
    repositories {
        mavenLocal()
    }
}
```

**Comment by JasMSS** [comment]
我的项目也是，引入fastdex之后，编译反而更慢了（已关闭instant run，使用了useCustomCompile=true）。原先7~8分钟，现在10分钟。而且GradleConsole中会打印大量的 “==fastdex inject:xx\……\xxx.java” 这样的日志。


平台：windows
fastdex版本：0.8.8
gradle版本:3.0.1

**Comment by JasMSS** [comment]
先直接用AndroidStudio的run之后（8分钟），没改任何代码的情况下，在控制台执行gradlew.bat fastdexOfficalQsDebug，居然也要13分钟。
